---
apiVersion: v1
data:
  COST: OPS
  ENV: PROD
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: db-server

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-prod
  labels:
    app: myapp
    type: prod
spec:
  containers:
    - name: nginx-container
      image: nginx
      envFrom:
        - configMapRef:
            name: db-server


############################################################################################################################

You can use ConfigMap-defined environment variables in the command and args of a container using the $(VAR_NAME) Kubernetes substitution syntax.

---
apiVersion: v1
data:
  command: sleep
  args: "10000"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: db-server
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-prod
  labels:
    app: myapp
    type: prod
spec:
  containers:
    - name: nginx-container
      image: nginx
      command: [ "/bin/echo", "$(COMMAND1)", "$(ARGUMENTS1)" ]
      env:
        - name: COMMAND1
          valueFrom:
            configMapKeyRef:
              name: db-server
              key: command

        - name: ARGUMENTS1
          valueFrom:
            configMapKeyRef:
              name: db-server
              key: args