---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-prod
    labels:
        type: prod
spec:
    replicas: 3
    selector:
        matchLabels:
          type: prod

    template:
        metadata:
          name: myapp-prod
          labels:
            type: prod
        spec:
            containers:
             - name: myapp-prod
               image: nginx


---

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-demo
    labels:
        type: demo
spec:
    replicas: 3
    selector:
        matchLabels:
          type: demo

    template:
        metadata:
          name: myapp-demo
          labels:
            type: demo
        spec:
            containers:
             - name: myapp-demo
               image: nginx
               command: ["echo"]
               args: ["Hello", "World!!"]

